version: '3'
services:
  rails:
    build: .
    command: sh -c "bundle install; rails s -b 0.0.0.0"
    container_name: educamasters
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      db: 
        condition: service_started
  db:
    image: postgres:13.4-buster
    ports:
      - 5342:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - educamasters_data:/var/lib/postgresql/data
volumes:
  educamasters_data:
  